version: '3.7'

services:

  dmeetflow_front:
    image: fabianbello/dmeetflow_front:v1.0.2
    container_name: dmeetflow_front
    env_file: .env
    ports:
      - 4200:80
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_api-gateway:
    image: fabianbello/dmeetflow_api-gateway:v1.0.0
    container_name: dmeetflow_api-gateway
    env_file: .env
    ports:
      - 80:3000
      - 82:82
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow
      
  dmeetflow_microservice-meetings:
    image: fabianbello/dmeetflow_microservice-meetings:v1.0.0
    container_name: dmeetflow_microservice-meetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow
      
  microservice-users:
    image: fabianbello/microservice-users:v31
    container_name: microservice-users
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_microservice-premeetings:
    image: fabianbello/dmeetflow_microservice-premeetings:v1.0.0
    container_name: dmeetflow_microservice-premeetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_microservice-postmeetings:
    image: fabianbello/dmeetflow_microservice-postmeetings:v1.0.0
    container_name: dmeetflow_microservice-postmeetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_microservice-meetingminutes:
    image: fabianbello/dmeetflow_microservice-meetingminutes:v1.0.0
    container_name: dmeetflow_microservice-meetingminutes
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_microservice-notifications:
    image: fabianbello/dmeetflow_microservice-notifications:v1.0.0
    container_name: dmeetflow_microservice-notifications
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_microservice-inmeetings:
    image: fabianbello/dmeetflow_microservice-inmeetings:v1.0.0
    container_name: dmeetflow_microservice-inmeetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow
      
  dmeetflow_microservice-elements:
    image: fabianbello/dmeetflow_microservice-elements:v1.0.0
    container_name: dmeetflow_microservice-elements
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow
  
  dmeetflow_microservice-projects:
    image: fabianbello/dmeetflow_microservice-projects:v1.0.0
    container_name: dmeetflow_microservice-projects
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_microservice-reminders:
    image: fabianbello/dmeetflow_microservice-reminders:v1.0.0
    container_name: dmeetflow_microservice-reminders
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow

  dmeetflow_microservice-tasks:
    image: fabianbello/dmeetflow_microservice-tasks:v1.0.0
    container_name: dmeetflow_microservice-tasks
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow
  
  dmeetflow_microservice-kanban:
    image: fabianbello/dmeetflow_microservice-kanban:v1.0.0
    container_name: dmeetflow_microservice-kanban
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_dmeetflow
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_dmeetflow

  mysql:
    image: mysql:latest
    container_name: mysql-microservice-users
    volumes:
      - ./sql-data/db:/var/lib/mysql22
    ports:
      - 5000:3306
    hostname: 'hostdbusers'
    environment:
      MYSQL_DATABASE: 'dbusers'
      MYSQL_USER: 'fabian'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - ms_dmeetflow

networks:
  ms_dmeetflow:
