version: '3.7'

services:

  front:
    image: fabianbello/meetflowfront:v40
    container_name: meetflowfront
    env_file: .env
    ports:
      - 4200:80
    restart: always
    networks:
      - ms_meetflow
      
  app:
    image: fabianbello/api-meetflow-m:v1
    container_name: api-meetflow-m
    env_file: .env
    ports:
      - 80:3000
    restart: always
    networks:
      - ms_meetflow
  
    image: fabianbello/app_meetflow:v6
    container_name: app_meetflow
    env_file: .env
    ports:
      - 81:3001
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
  
  microservice-projects:
    image: fabianbello/microservice-projects:v6
    container_name: microservice-projects
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-guests:
    image: fabianbello/microservice-guests:v6
    container_name: microservice-guests
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-users:
    image: fabianbello/microservice-users:v6
    container_name: microservice-users
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
  
  microservice-meetings:
    image: fabianbello/microservice-meetings:v6
    container_name: microservice-meetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_meetflow

  mysql:
    image: mysql:latest
    container_name: mysql-microservice-users
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - 5000:3306
    hostname: 'hostdbusers'
    environment:
      MYSQL_DATABASE: 'dbusers'
      MYSQL_USER: 'fabian'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - ms_meetflow

networks:
  ms_meetflow:
