version: '3.7'

services:

  front:
    image: fabianbello/meetflowfront:v454
    container_name: meetflowfront
    env_file: .env
    ports:
      - 4200:80
    restart: always
    networks:
      - ms_meetflow

  app:
    image: fabianbello/app_meetflow:v65
    container_name: app_meetflow
    env_file: .env
    ports:
      - 80:3000
      - 82:82
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
      
  microservice-meetings:
    image: fabianbello/microservice-meetings:v36
    container_name: microservice-meetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
      
  microservice-users:
    image: fabianbello/microservice-users:v31
    container_name: microservice-users
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-premeetings:
    image: fabianbello/microservice-premeetings:v21
    container_name: microservice-premeetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-postmeetings:
    image: fabianbello/microservice-postmeetings:v21
    container_name: microservice-postmeetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-meetingminutes:
    image: fabianbello/microservice-meetingminutes:v25
    container_name: microservice-meetingminutes
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-notifications:
    image: fabianbello/microservice-notifications:v43
    container_name: microservice-notifications
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-inmeetings:
    image: fabianbello/microservice-inmeetings:v21
    container_name: microservice-inmeetings
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
      
  microservice-elements:
    image: fabianbello/microservice-elements:v42
    container_name: microservice-elements
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
  
  microservice-projects:
    image: fabianbello/microservice-projects:v21
    container_name: microservice-projects
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-guests:
    image: fabianbello/microservice-guests:v20
    container_name: microservice-guests
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-reminders:
    image: fabianbello/microservice-reminders:v22
    container_name: microservice-reminders
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow

  microservice-tasks:
    image: fabianbello/microservice-tasks:v21
    container_name: microservice-tasks
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
  
  microservice-kanban:
    image: fabianbello/microservice-kanban:v21
    container_name: microservice-kanban
    env_file: .env
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - ms_meetflow
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_meetflow

  mysql:
    image: mysql:latest
    container_name: mysql-microservice-users
    volumes:
      - ./sql-data/db:/var/lib/mysql22
    ports:
      - 5000:3306
    hostname: 'hostdbusers'
    environment:
      MYSQL_DATABASE: 'dbusers'
      MYSQL_USER: 'fabian'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - ms_meetflow

networks:
  ms_meetflow:
